name: base
on: [push, pull_request]
jobs:
  general:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: code quality
        run: npm run prettier:check && yarn run lint
      # - name: publish
      - run: git config --global user.email "njkznu@gmail.com"
      - run: git config --global user.name "kuzanatoliy"
      # - run: git checkout origin/gh-pages
      # - run: git reset --hard HEAD~1
      # - run: git push
      # - run: git checkout ${GITHUB_REF##*/}
      - run: git add -f dist
      - run: git commit -am "deploy preview to ng-pages"
      # - run: git push origin --delete gh-pages
      # - run: git subtree pull --prefix dist origin gh-pages
      # - run: git subtree push --prefix dist origin gh-pages
      - run: git push origin `git subtree split --prefix dist deploy`:refs/heads/gh-pages --force
      - run: git reset --hard HEAD~1
