name: deploy
on:
  push:
    branches:
      - master
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm install
        run: yarn run lint
      - name: build
        run: npm run build
      - name: deploy
        run: |
          git config --global user.email "njkznu@gmail.com"
          git config --global user.name "kuzanatoliy"
          git add -f dist
          git commit -am "deploy preview to ng-pages"
          git push origin `git subtree split --prefix dist deploy`:refs/heads/gh-pages --force
          git reset --hard HEAD~1
